# Generated by Django 4.0.3 on 2022-03-21 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crimeID', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=225)),
                ('sourceURL', models.URLField(default='', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('notes', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('year2013', models.PositiveIntegerField()),
                ('year2014', models.PositiveIntegerField()),
                ('year2015', models.PositiveIntegerField()),
                ('year2016', models.PositiveIntegerField()),
                ('year2017', models.PositiveIntegerField()),
                ('year2018', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('personID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(110)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='U', max_length=10)),
                ('status', models.CharField(choices=[('Arrested', 'Arrested'), ('Killed', 'Killed'), ('Injured', 'Injured'), ('Unharmed', 'Unharmed'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('personType', models.CharField(choices=[('Subject-Suspect', 'Subject-Suspect'), ('Victim', 'Victim'), ('Unknown', 'Unknown')], default='Unknown', max_length=15)),
                ('inCrime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crime')),
            ],
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('gunID', models.IntegerField(primary_key=True, serialize=False)),
                ('stolen', models.BooleanField(default=False)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crime')),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
    ]
