# Generated by Django 4.0.3 on 2022-03-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gunID', models.IntegerField()),
                ('crimeID', models.IntegerField()),
                ('stolen', models.BooleanField()),
            ],
        ),
    ]
