# Generated by Django 4.0.3 on 2022-03-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_personid_person_pid_remove_person_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
