# Generated by Django 4.0.3 on 2022-03-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_crime_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12),
        ),
        migrations.AlterField(
            model_name='crime',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12),
        ),
    ]
